### ISSUE TITLE
Question: Will it be possible?

### ISSUE THREAD

**Issue by mato75** [S-YOU/doTA#1]
Use with angular-vs-repeat library.

The library is ql, but there is still a problem with the $digest cycle. I use it in my table, and if table doesn’t have to many columns it is ok, but as soon as you have more a lot of columns (horizontal), the digest cycle is not fast enough.

I know of horizontal scrolling also, but columns in the table have dynamic width, so I cannot use horizontal scrolling from angular-vs-repeat lib. 

Do you think this lib would fix the $digest cycle?

**Comment by S-YOU** [comment]
Could you show me your html table template?

This lib parse HTML itself and bind data from $scope and write to DOM itself, so, angular $digest shouldn't be problem.

But this library support only limited set of HTMLs, and angular attributes, so, I need to see, what kind of HTML you have, so, I can suggest it is doable or not.

**Comment by mato75** [comment]
http://jsbin.com/yagoyoxabi/3/edit?html,css,js,output

Something like this.

**Comment by S-YOU** [comment]
This is how to use (without angular-vs-repeat)
http://jsbin.com/firanirexe/1/edit?html,css,js,output
The whole table is written to dom as static html with no watchers.

If data is dynamic, you might need to add, `watch="nameArray"` to dota-render tag,
and if there is two way binding, you will need `compile=1` in the dota-render tag too, and will probably need `scope=1` to make new scope to make sure there is no watchers left behind when you leave the scope.

**Comment by mato75** [comment]
Ok, I need angular-vs-repeat, because we are moving/animating navigation holder, and with that table is moving right, so if there is to much elements in the html, navigation is really laggy and slow, and with angular-vs-repeat, we fix this issue.

**Comment by S-YOU** [comment]
I see. looks like angular-vs-repeat parse ng-repeat itself, and this lib also parse itself. so, they are basically taking priority over each other. currently no idea to work together both library on same tag for now.

**Comment by mato75** [comment]
Thx, for checking it out.

**Comment by S-YOU** [comment]
angular-vs-repeat write sub directives `vs-set-offset` on each item on the fly, 
and using $emit and $broadcast to communicate with those.
So, to make this lib to work with vs-repeat, I think half of vs-repeat need to rewrite not to use vs-set-offset directive to be most effective.

btw, using angular 1.3 one time binding syntax `{{::` or `ng-bind="::name"` on inner html content
can improve to make less watches I beleive.

**Comment by mato75** [comment]
I can use one time binding in angular-vs-repeat, but the I need to track row by some id, and that is slower then if I use ng-bind. 

Inner html content, like using ng-bing-html?

**Comment by S-YOU** [comment]
Any chance you could setup jsbin more close to your real data? 
like similar amount of table columns, dynamic width, with moving/animating navigation.

with angular-vs-repeat there is only few watchers left, so can't realize why $digest cycle still having problem.

**Comment by mato75** [comment]
http://jsbin.com/dubulukode/1/edit?html

**Comment by S-YOU** [comment]
There is 3 ng-repeat, you using angular-vs-repeat on outmost one?

**Comment by mato75** [comment]
3 ngRepeats yes, that is why it is slow. to many watchers that angularjs needs to check. What I did now is, that I created html for every tr, and only watch tr ngRepat, no longer other.

**Comment by S-YOU** [comment]
I see. Apart from vs-repeat, this one should work same as your html writing service
http://jsbin.com/fetejixeya/1/edit
but without binding on val

**Comment by mato75** [comment]
thx man I will take a look. You are awesome, really fast responses and really eager to help.

You are the BOMB!!!

**Comment by S-YOU** [comment]
My pleasure, drop me message any time.
